name: Run unit tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ 1.20 ]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: bap_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run migrations with Docker
        run: |
          docker run -v $(pwd)/DDL:/migrations --network host migrate/migrate -path=/migrations/ -database "postgresql://test:test@127.0.0.1:5432/bap_test?sslmode=disable" -verbose up

      - name: cp env
        run: cp .env.example .env

      - name: Start LocalStack
        working-directory: .
        run: docker-compose up -d --build localstack
        env:
          SERVER_PORT: 8080
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: bap
          TEST_POSTGRES_HOST: localhost
          TEST_POSTGRES_PORT: 5432
          TEST_POSTGRES_USER: test
          TEST_POSTGRES_PASSWORD: test
          TEST_POSTGRES_DATABASE: bap_test

      - name: Test
        env:
          SERVER_PORT: 8080
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: bap
          TEST_POSTGRES_HOST: localhost
          TEST_POSTGRES_PORT: 5432
          TEST_POSTGRES_USER: test
          TEST_POSTGRES_PASSWORD: test
          TEST_POSTGRES_DATABASE: bap_test
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_ENDPOINT: http://localhost:4566
          AWS_ENDPOINT_LOCAL: http://localhost:4566
          AWS_S3_BUCKET_NAME: bank-banner-images

        run: go test ./...